Closes #51 : Added index.d.ts + documentation for javascript and typescript
piuccio/cowsay pull request #59
Opened 2020-08-12 20:37 UTC by iArmann

### Closes #51 : Added **`index.d.ts`** + **documentation** for _Javascript_ and _Typescript_

2021-02-24 18:09 UTC, lachieh requested changes
This all looks good to be, aside from a few the y and w being switched in some of the examples. I'm not the owner but I have confirmed that this file works as expected. I appreciate the updated readme with examples too.

@piuccio if you're good with the README.md changes, this is good from a TS perspective.

2021-02-24 18:09 UTC, lachieh commented on index.d.ts
> + * - #### `y` : wired
```suggestion
 * - #### `w` : wired
 * - #### `y` : youthful
```

2021-02-24 18:09 UTC, lachieh commented on index.d.ts
> + * - #### `y` : wired
```suggestion
 * - #### `w` : wired
 * - #### `y` : youthful
```

2021-02-24 18:09 UTC, lachieh commented on index.js
> + * - #### `y` : wired
```suggestion
 * - #### `w` : wired
 * - #### `y` : youthful
```

2021-02-24 18:09 UTC, lachieh commented on index.js
> + * - #### `y` : wired
```suggestion
 * - #### `w` : wired
 * - #### `y` : youthful
```

2021-02-24 18:09 UTC, lachieh commented on index.d.ts
> +    y?: boolean, // wired
```suggestion
    w?: boolean, // wired
    y?: boolean, // youthful
```

2021-02-25 06:26 UTC, piuccio approved these changes

2021-02-25 06:27 UTC, merged